"""Central API and model-output size limits for the local MVP."""

SOURCE_APP_MAX_LENGTH = 200
SOURCE_TITLE_MAX_LENGTH = 500
SOURCE_URL_MAX_LENGTH = 2_048
USER_NOTE_MAX_LENGTH = 4_000
SEARCH_QUERY_MAX_LENGTH = 512

ENRICHMENT_TITLE_MAX_LENGTH = 200
ENRICHMENT_TEXT_MAX_LENGTH = 2_000
ENRICHMENT_LIST_MAX_ITEMS = 20
ENRICHMENT_LIST_ITEM_MAX_LENGTH = 300
