"""Central API and model-output size limits for the local MVP."""

SOURCE_APP_MAX_LENGTH = 200
SOURCE_TITLE_MAX_LENGTH = 500
SOURCE_URL_MAX_LENGTH = 2_048
SELECTED_TEXT_MAX_LENGTH = 12_000
USER_NOTE_MAX_LENGTH = 4_000
SEARCH_QUERY_MAX_LENGTH = 512
SCREENSHOT_MAX_BYTES = 8 * 1024 * 1024
SCREENSHOT_BASE64_MAX_LENGTH = 11_184_812
IMAGE_CAPTURE_METADATA_MAX_LENGTH = 8_192
OCR_TEXT_MAX_LENGTH = SELECTED_TEXT_MAX_LENGTH
IMAGE_MAX_WIDTH = 20_000
IMAGE_MAX_HEIGHT = 20_000
IMAGE_MAX_PIXELS = 40_000_000

ENRICHMENT_TITLE_MAX_LENGTH = 200
ENRICHMENT_TEXT_MAX_LENGTH = 2_000
ENRICHMENT_LIST_MAX_ITEMS = 20
ENRICHMENT_LIST_ITEM_MAX_LENGTH = 300

USER_TITLE_MAX_LENGTH = ENRICHMENT_TITLE_MAX_LENGTH
USER_DETAIL_MAX_LENGTH = ENRICHMENT_TEXT_MAX_LENGTH
USER_LIST_MAX_ITEMS = ENRICHMENT_LIST_MAX_ITEMS
USER_LIST_ITEM_MAX_LENGTH = ENRICHMENT_LIST_ITEM_MAX_LENGTH
